name: Docker Build and Cache

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
            go-mod-cache
            go-build-cache
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Inject go-build-cache into docker
      uses: reproducible-containers/buildkit-cache-dance@v3
      with:
        cache-map: |
          {
            "go-mod-cache": "/go/pkg/mod",
            "go-build-cache": "/root/.cache/go-build"
          }

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max